import { useState, useRef, useEffect, useCallback } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { apiFetch } from "./client";
import { streamingFetch } from "./streaming";
import { useAIConfigs } from "./ai-config";

// ─── Types ───

interface BriefingResponse {
  briefing: {
    sessionId: string;
    content: string;
    generatedAt: string;
  } | null;
}

interface BriefingSummaryResponse {
  overdueTasks: number;
  dueTodayTasks: number;
  todayEvents: number;
  overdueItems: Array<{ title: string; dueDate: string }>;
}

// ─── Briefing Hook ───

export function useBriefing() {
  const qc = useQueryClient();
  const [streamingContent, setStreamingContent] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [isError, setIsError] = useState(false);
  const abortRef = useRef<AbortController | null>(null);
  const hasAutoGeneratedRef = useRef(false);

  const { data: aiConfigData } = useAIConfigs();
  const hasAI = (aiConfigData?.configs ?? []).some(
    (c) => c.isActive && c.isValid
  );

  const briefingQuery = useQuery({
    queryKey: ["briefing"],
    queryFn: () => apiFetch<BriefingResponse>("/brett/briefing"),
    enabled: hasAI,
  });

  const cachedBriefing = briefingQuery.data?.briefing ?? null;

  const content =
    isGenerating && streamingContent
      ? streamingContent
      : cachedBriefing?.content ?? null;

  const regenerate = useCallback(async () => {
    if (isGenerating) return;

    setStreamingContent("");
    setIsGenerating(true);
    setIsError(false);

    const controller = new AbortController();
    abortRef.current = controller;

    try {
      for await (const chunk of streamingFetch(
        "/brett/briefing/generate",
        {},
        controller.signal
      )) {
        if (controller.signal.aborted) break;

        if (chunk.type === "text") {
          setStreamingContent((prev) => prev + chunk.content);
        } else if (chunk.type === "error") {
          setIsError(true);
        }
      }
    } catch (err) {
      if ((err as Error).name !== "AbortError") {
        setIsError(true);
      }
    } finally {
      setIsGenerating(false);
      abortRef.current = null;
      qc.invalidateQueries({ queryKey: ["briefing"] });
    }
  }, [isGenerating, qc]);

  const cancel = useCallback(() => {
    if (abortRef.current) {
      abortRef.current.abort();
      abortRef.current = null;
    }
    setIsGenerating(false);
  }, []);

  // Cleanup: abort any in-flight generation on unmount
  useEffect(() => {
    return () => {
      if (abortRef.current) {
        abortRef.current.abort();
      }
    };
  }, []);

  // Auto-generate on first app open if no cached briefing
  useEffect(() => {
    if (
      hasAI &&
      !briefingQuery.isLoading &&
      !cachedBriefing &&
      !hasAutoGeneratedRef.current &&
      !isGenerating
    ) {
      hasAutoGeneratedRef.current = true;
      regenerate();
    }
  }, [hasAI, briefingQuery.isLoading, cachedBriefing, isGenerating, regenerate]);

  return {
    content,
    isLoading: briefingQuery.isLoading,
    isGenerating,
    isError,
    hasAI,
    hasBriefing: !!cachedBriefing || (isGenerating && !!streamingContent),
    generatedAt: cachedBriefing?.generatedAt ?? null,
    regenerate,
    cancel,
  };
}

// ─── Summary Hook (no AI required) ───

export function useBriefingSummary() {
  return useQuery({
    queryKey: ["briefing-summary"],
    queryFn: () => apiFetch<BriefingSummaryResponse>("/brett/briefing/summary"),
  });
}
