import Foundation

/// Single source of truth for how a `@Model` exposes its mutable fields to
/// the sync engine.
///
/// The old pattern had four parallel switch statements per model
/// (`snapshot`, `applyChanges`, `payloadForUpdate`, `previousValuesForChanges`)
/// that had to stay in lock-step. Missing a field in any one of them silently
/// dropped it from conflict resolution or the wire payload — a classic
/// "add-a-field, lose data" foot-gun.
///
/// Models now declare one `Field` enum + two accessors (`value(for:)` and
/// `set(_:for:)`). All four derived operations are generated by the protocol
/// extension, guaranteeing they stay consistent.
///
/// `Field.rawValue` MUST match the server's JSON key for that field (e.g.
/// `.description` → `"description"` even though the Swift property is
/// `itemDescription`). Unknown keys in inbound changesets are silently ignored
/// so the server can add fields without breaking older clients.
protocol MutableFieldModel: AnyObject {
    associatedtype Field: RawRepresentable & CaseIterable & Hashable where Field.RawValue == String

    /// Whitelist of fields the client is allowed to mutate and send to the
    /// server. Typically `Field.allCases` minus any read-only or
    /// server-assigned fields (id, userId, createdAt, deletedAt, sync meta).
    static var mutableFields: [Field] { get }

    /// Current value of a field. Optional fields return `nil` when unset;
    /// value types are returned in their native Swift form (Date as Date,
    /// not ISO string). Wire-format conversion happens in `JSONCodec`.
    func value(for field: Field) -> Any?

    /// Write a value into a field. Implementations should:
    ///  - Treat `NSNull` and `nil` equivalently (both mean "clear" for
    ///    optional fields, no-op for non-optional ones).
    ///  - Silently ignore type mismatches (e.g. a server sends a String
    ///    where the client expects a Date — log and skip rather than crash).
    func set(_ value: Any?, for field: Field)
}

// MARK: - Derived operations

extension MutableFieldModel {
    /// Full snapshot of every mutable field. Used as `beforeSnapshot` for
    /// rollback and as the baseline for conflict resolution.
    func mutableFieldSnapshot() -> [String: Any] {
        var out: [String: Any] = [:]
        for field in Self.mutableFields {
            // Store `nil` as `NSNull` so JSON encoding preserves the intent
            // (a missing key would be ambiguous — "clear this field" vs
            // "don't touch this field"). The mutation queue relies on this
            // to compute per-field diffs server-side.
            out[field.rawValue] = value(for: field) ?? NSNull()
        }
        return out
    }

    /// Snapshot restricted to the field names supplied. Skips unknown
    /// names silently — allows callers to pass through inbound changeset
    /// keys without pre-filtering.
    func previousValues(forFields names: [String]) -> [String: Any] {
        var out: [String: Any] = [:]
        for name in names {
            guard let field = Field(rawValue: name) else { continue }
            out[name] = value(for: field) ?? NSNull()
        }
        return out
    }

    /// Apply a string-keyed changeset (from the mutation queue when
    /// rehydrating, or from a server `apply` during conflict resolution).
    func apply(changes: [String: Any]) {
        for (key, newValue) in changes {
            guard let field = Field(rawValue: key) else { continue }
            set(newValue, for: field)
        }
    }

    /// Build a PATCH payload containing only the supplied fields. Returns
    /// raw Swift types; pair with `JSONCodec.encode` for wire format.
    func patchPayload(for changedFields: [String]) -> [String: Any] {
        var out: [String: Any] = [:]
        for name in changedFields {
            guard let field = Field(rawValue: name) else { continue }
            out[name] = value(for: field) ?? NSNull()
        }
        return out
    }
}
