// scripts/backgrounds/write-doc.ts
//
// Generates docs/backgrounds.md from the manifest + attributions. Includes a
// sampled wash color per image (the same 50–65% vertical band the iOS
// WashColorSampler uses), so UI work can pick "test against this extreme"
// from the catalog without hand-eyeballing.
//
// Run: pnpm tsx scripts/backgrounds/write-doc.ts

import fs from "fs";
import path from "path";
import sharp from "sharp";

const ROOT = path.resolve(__dirname, "../..");
const MANIFEST = JSON.parse(fs.readFileSync(path.join(ROOT, "packages/business/src/data/background-manifest.json"), "utf-8"));
const ATTR = JSON.parse(fs.readFileSync(path.join(ROOT, "packages/business/src/data/image-attributions.json"), "utf-8"));
const BG_DIR = path.join(ROOT, "backgrounds");
const OUT = path.join(ROOT, "docs/backgrounds.md");

const PROD_BASE = "https://api.brett.brentbarkman.com/public/backgrounds";

const SEG_ORDER = ["dawn", "morning", "afternoon", "goldenHour", "evening", "night"] as const;
const TIER_ORDER = ["light", "moderate", "packed"] as const;
const SEG_BLURB: Record<string, { hours: string; mood: string }> = {
  dawn:       { hours: "05–07", mood: "cool blues / pinks / pastels, low pre-dawn haze" },
  morning:    { hours: "07–12", mood: "clear, bright, optimistic — blue / cream tones" },
  afternoon:  { hours: "12–17", mood: "warm mid-day clarity, full sun" },
  goldenHour: { hours: "17–19", mood: "amber, low-angle warm light, deep oranges / golds" },
  evening:    { hours: "19–21", mood: "post-sunset cooling blues / violets, low saturation" },
  night:      { hours: "21–05", mood: "deep, low chroma, moon / starlit" },
};
const TIER_BLURB: Record<string, string> = {
  light:    "airy, distant, breathing room — calm day",
  moderate: "balanced, layered — typical day",
  packed:   "grounded, intimate, enveloping — busiest day (visual calm so the UI can carry the load)",
};

async function sampleWash(landscapePath: string): Promise<string> {
  // Mirrors WashColorSampler.swift: middle 50–65% vertical band, average RGB.
  const meta = await sharp(landscapePath).metadata();
  const h = meta.height ?? 0;
  const sy = Math.floor(h * 0.50);
  const sh = Math.floor(h * 0.15);
  const { data, info } = await sharp(landscapePath)
    .extract({ left: 0, top: sy, width: meta.width!, height: sh })
    .resize(64, 32, { fit: "fill" })
    .raw()
    .toBuffer({ resolveWithObject: true });
  let r = 0, g = 0, b = 0, n = 0;
  const stride = info.channels;
  for (let i = 0; i < data.length; i += stride) {
    r += data[i]; g += data[i + 1]; b += data[i + 2]; n++;
  }
  r = Math.round(r / n); g = Math.round(g / n); b = Math.round(b / n);
  return "#" + [r, g, b].map((v) => v.toString(16).padStart(2, "0")).join("").toUpperCase();
}

async function main() {
  const photoSet = MANIFEST.sets.photography as Record<string, Record<string, string[]>>;
  const lines: string[] = [];

  lines.push("# Backgrounds");
  lines.push("");
  lines.push("Auto-generated by `scripts/backgrounds/write-doc.ts` — do not edit by hand. Regenerate after any wallpaper change.");
  lines.push("");
  lines.push("## How selection works");
  lines.push("");
  lines.push("The app picks a wallpaper based on two axes:");
  lines.push("");
  lines.push("- **Time segment** — dawn / morning / afternoon / goldenHour / evening / night, derived from the local hour (`getTimeSegment` in `@brett/business`).");
  lines.push("- **Busyness tier** — light / moderate / packed, derived from today's meeting + task count vs. the user's 14-day baseline (`getBusynessTier`).");
  lines.push("");
  lines.push("Within a slot, images rotate every 10 minutes with shuffle-without-replacement (`selectImage`).");
  lines.push("");
  lines.push("Each wallpaper has two physical files: a **landscape** (2560×1440, desktop) and a **portrait** (1290×2796, iOS) crop.");
  lines.push("");
  lines.push("On iOS the middle 50–65% band of the landscape is sampled to a solid **wash color** that paints the bed for non-Today pages (`WashColorSampler.swift`). The wash hex is included below per image — useful when you're designing something that has to read against the wallpaper bed.");
  lines.push("");
  lines.push("## Catalog");
  lines.push("");

  let total = 0;
  let landscapeBytes = 0;
  let portraitBytes = 0;

  for (const seg of SEG_ORDER) {
    const tiers = photoSet[seg];
    if (!tiers) continue;
    const blurb = SEG_BLURB[seg];
    lines.push(`### ${seg}  · ${blurb.hours}h · ${blurb.mood}`);
    lines.push("");

    for (const tier of TIER_ORDER) {
      const paths = tiers[tier];
      if (!paths || paths.length === 0) continue;
      lines.push(`#### ${seg} / ${tier}`);
      lines.push(`_${TIER_BLURB[tier]}_`);
      lines.push("");
      lines.push("| # | Wash | Landscape | Portrait | Photographer |");
      lines.push("|---|------|-----------|----------|--------------|");

      for (let i = 0; i < paths.length; i++) {
        const slotPath = paths[i];
        const portraitPath = slotPath.replace(/^photo\//, "photo-portrait/");
        const landscapeFile = path.join(BG_DIR, slotPath);
        const portraitFile = path.join(BG_DIR, portraitPath);

        const wash = await sampleWash(landscapeFile);
        const attr = ATTR[slotPath] ?? { photographer: "Unknown", unsplashUrl: "" };
        const photog = attr.unsplashUrl
          ? `[${attr.photographer}](${attr.unsplashUrl})`
          : attr.photographer;

        const landscapeUrl = `${PROD_BASE}/${slotPath}`;
        const portraitUrl = `${PROD_BASE}/${portraitPath}`;
        lines.push(`| ${i + 1} | \`${wash}\` | [\`${slotPath}\`](${landscapeUrl}) | [\`${portraitPath}\`](${portraitUrl}) | ${photog} |`);

        if (fs.existsSync(landscapeFile)) landscapeBytes += fs.statSync(landscapeFile).size;
        if (fs.existsSync(portraitFile))  portraitBytes  += fs.statSync(portraitFile).size;
        total++;
      }
      lines.push("");
    }
  }

  lines.push("## Totals");
  lines.push("");
  lines.push(`- **${total}** wallpapers across ${Object.values(photoSet).reduce((n, t) => n + Object.keys(t).length, 0)} slots`);
  lines.push(`- Landscapes: ${(landscapeBytes / 1024 / 1024).toFixed(1)} MB`);
  lines.push(`- Portraits: ${(portraitBytes / 1024 / 1024).toFixed(1)} MB`);
  lines.push("");
  lines.push("## Testing patterns");
  lines.push("");
  lines.push("When designing UI that sits on a wallpaper (glass cards, briefing prose, nav, hero text), test against the extremes from the wash column above:");
  lines.push("");
  lines.push("- The **lightest** washes (`#C0+`) stress dark-on-light readability — watch for white text disappearing, glass cards getting overpowered.");
  lines.push("- The **darkest** washes (`#3-`) stress light-on-dark — watch for glass tinting getting muddy, text-shadow shifting.");
  lines.push("- The **most saturated** washes (deep amber / cobalt / teal) stress neutral chrome — does the gold accent fight the wallpaper?");
  lines.push("- The **portrait** crop is always center-vertical on iOS, so if a landscape's interest is in the left or right thirds, the portrait will look different from the desktop — check both columns.");
  lines.push("");
  lines.push("Open `scripts/backgrounds/gallery.html` (rebuild with `pnpm tsx scripts/backgrounds/build-gallery.ts` and serve via `pnpm preview` config) for an at-a-glance side-by-side with the real Today UI overlaid.");
  lines.push("");

  fs.writeFileSync(OUT, lines.join("\n"));
  console.log(`Wrote ${OUT}`);
  console.log(`  ${total} wallpapers cataloged`);
}

main().catch((err) => { console.error(err); process.exit(1); });
