/**
 * Regression test for the overnight-skeleton briefing bug.
 *
 * History: `useBriefing` cached `/brett/briefing` under `["briefing"]` with
 * no day component, and gated auto-generation behind a once-per-mount ref.
 * If the desktop app stayed open past local midnight, the cached briefing
 * stuck at yesterday's value and the auto-gen ref blocked a fresh
 * generation, so users saw the skeleton even though the server would
 * return Day N's briefing on a fresh fetch (or generate it on demand).
 *
 * Fix: today's key participates in the queryKey, AND the auto-gen ref
 * resets on day rollover.
 */
import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { renderHook, waitFor, act } from "@testing-library/react";
import React from "react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

let mockTodayKey = "2026-05-06T00:00:00.000Z";
vi.mock("../../hooks/useTodayKey", () => ({
  useTodayKey: () => mockTodayKey,
}));

vi.mock("../ai-config", () => ({
  useAIConfigs: () => ({
    data: { configs: [{ isActive: true, isValid: true }] },
  }),
}));

vi.mock("../client", () => ({
  apiFetch: vi.fn(),
}));

vi.mock("../streaming", () => ({
  streamingFetch: vi.fn(),
}));

import { apiFetch } from "../client";
import { streamingFetch } from "../streaming";
import { useBriefing } from "../briefing";

const mockApiFetch = vi.mocked(apiFetch);
const mockStreamingFetch = vi.mocked(streamingFetch);

function setupQueryClient() {
  const qc = new QueryClient({
    defaultOptions: { queries: { retry: false, staleTime: 0 } },
  });
  const wrapper = ({ children }: { children: React.ReactNode }) =>
    React.createElement(QueryClientProvider, { client: qc }, children);
  return { qc, wrapper };
}

beforeEach(() => {
  mockTodayKey = "2026-05-06T00:00:00.000Z";
  mockApiFetch.mockResolvedValue({ briefing: null });
  // streamingFetch returns an async iterator — yield nothing so regenerate
  // resolves quickly in tests without producing content.
  mockStreamingFetch.mockImplementation(
    async function* () {
      // empty
    } as unknown as typeof streamingFetch,
  );
});

afterEach(() => {
  vi.clearAllMocks();
});

describe("useBriefing day rollover", () => {
  it("uses a queryKey that includes todayKey so cache invalidates at midnight", async () => {
    const { qc, wrapper } = setupQueryClient();
    renderHook(() => useBriefing(), { wrapper });

    await waitFor(() => {
      expect(mockApiFetch).toHaveBeenCalledWith("/brett/briefing");
    });

    // The cache must be keyed by today, not by a bare ["briefing"] string.
    // Without today in the key, the same cached entry serves both Day 1 and
    // Day 2, and the user sees yesterday's briefing forever.
    const briefingKeys = qc
      .getQueryCache()
      .getAll()
      .map((q) => q.queryKey)
      .filter((k) => Array.isArray(k) && k[0] === "briefing");
    expect(briefingKeys.length).toBeGreaterThanOrEqual(1);
    const flat = briefingKeys.flat();
    expect(flat).toContain(mockTodayKey);
  });

  it("re-runs auto-generation on day rollover when the new day has no briefing", async () => {
    const { wrapper } = setupQueryClient();
    const { rerender } = renderHook(() => useBriefing(), { wrapper });

    // Day 1: server returns null → auto-gen fires once.
    await waitFor(() => {
      expect(mockStreamingFetch).toHaveBeenCalledTimes(1);
    });

    // Day 2: same null result. Without the ref-reset, auto-gen would stay
    // gated by hasAutoGeneratedRef and never fire again.
    mockTodayKey = "2026-05-07T00:00:00.000Z";
    await act(async () => {
      rerender();
    });

    await waitFor(() => {
      expect(mockStreamingFetch).toHaveBeenCalledTimes(2);
    });
  });
});
